version: '3'

services:
  db:
    image: postgres:15
    restart: on-failure
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_pg_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_pg_pass}
      POSTGRES_DB: ${POSTGRES_DB:-app}

  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .

    restart: on-failure
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 9009
    #    Config for xDebug using serverName: Settings->PHP->Servers->Name = Docker
    environment:
      PHP_IDE_CONFIG: 'serverName=Docker'
    volumes:
      - ${PWD}:${DOCKER_APP_PATH}
      - /etc/timezone:/etc/timezone:ro
      - ${PWD}/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ${PWD}/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    working_dir: ${DOCKER_APP_PATH}
    depends_on:
      - db

  nginx:
    image: nginx:mainline-alpine
    restart: on-failure
    ports:
      - ${DOCKER_HTTP_PORT:-80}:80
    volumes:
      - ${PWD}:${DOCKER_APP_PATH}
      - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  node:
    image: node:16-alpine
    restart: on-failure
    volumes:
      - ${PWD}:${DOCKER_APP_PATH}
    working_dir: ${DOCKER_APP_PATH}
    command: yarn run watch
    depends_on:
      - nginx

volumes:
  db-data: